### ISSUE TITLE
Student Role in Resources Management

### ISSUE THREAD

**Issue by mstmustisnt** [mygod1980/al-library-backend#9]
@mygod1980 please clarify what kind of stuff users with student role can do.

**Comment by mygod1980** [comment]
students can view and download books

**Comment by mstmustisnt** [comment]
you mean *upload* I guess.

**Comment by mygod1980** [comment]
upload to library? no, admin only can upload (create) books.
student can download book to his computer. Or what?

**Comment by mstmustisnt** [comment]
Thank you. As I understand we don't need separate role for students since they have the same rights as plain users. I'll remove extra role then
